### PR TITLE
Support of the Radiator Thermostat Eurotronic SPIRITZ (Z-WAVE)

### PR DESCRIPTION
**Pull request by t0urista**
Support of the latest model of Eurotronic Z-WAVE Thermostat   SPIRTIZ

Attention, Thermostat can be reported with 3 different IDs, 328.3.1, 328.3.2 328.3.3, so 3 different definitions needed.

All SPIRIT ZWAVE values and paramaters are now defined and recognized by JEEDOM

modes Boost (Mode 15)  and Manual Valve Control (Mode 31) are only partially recognized because of OpenZWAVE demon not accepting mode higer than 12, so not related to the SPIRITZ as such

dummy_state (THERMOSTAT_STATE) and dummy_state_name (THERMOSTAT_STATE_NAME) defined to ensure that the Mobile Plugin can recognize it as thermostat.
Note that in the Mobile Plugin you can only have one temperature setting rotating button , so you need to choose whether you keep the temperature setting for the Heat Mode (by deselecting heat eco setpoint and heat eco setpoint info) or vice versa.  can be deselected in the Mobile custom setting (per plugin or per object)

### CODE REVIEW

**Comment by sarakha63** [comment]
Bonjour

Peux tu m'eclairer sur les deux commandes dummy_state

**Comment by t0urista** [comment]
Bonjour

j'ai créé 2 commandes additionnelles, dummy_state  de type THERMOSTAT_STATE et dummy_state_name de type THERMOSTAT_STATE_NAME, pour que l'objet THERMOSTAT tel que défini par le plugin mobile soit complet.
Grace a ces deux commandes, la vanne est reconnue naturellement comme un thermostat dans le plugin Mobile.

**Comment by enricobaros** [comment]
Bonjour, serait-il de faire passer cette PR ? Grand merci

**Comment by 3djc** [comment]
Je plussoie, testé sur 3 vannes de ce type !

**Pull request closed without merging**
